services:

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    depends_on:
      - auth-service
      - order-service
      - inventory-service
      - notification-service
    ports:
      - "8080:8080"
    working_dir: /app
    env_file:
      - .env.docker

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      auth_db:
        condition: service_healthy
    volumes:
      - ./secrets/jwt:/app/keys:ro
    working_dir: /app
    env_file:
      - .env.docker

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      order_db:
        condition: service_healthy
    working_dir: /app
    env_file:
      - .env.docker

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    depends_on:
      inventory_db:
        condition: service_healthy
    working_dir: /app
    env_file:
      - .env.docker

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      notification_db:
        condition: service_healthy
    working_dir: /app
    env_file:
      - .env.docker

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "cub", "zk-ready", "localhost:2181", "30" ]
      interval: 10s
      timeout: 5s
      retries: 10


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "9092:9092"
    env_file:
      - .env.docker
    environment:
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA_BOOTSTRAP_SERVERS_INTERNAL},EXTERNAL://${KAFKA_BOOTSTRAP_SERVERS_EXTERNAL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server ${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}" ]
      interval: 5s
      retries: 5
    volumes:
      - kafka_data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    env_file:
      - .env.docker
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}

  kafka-connect:
    build:
      context: ./debezium
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:

      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
      CONNECT_GROUP_ID: connect-cluster

      CONNECT_CONFIG_STORAGE_TOPIC: connect_configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect_offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect_status

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      #      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      #      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081

      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components

    depends_on:
      kafka:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/connectors" ]
      interval: 10s
      retries: 10

  debezium-init:
    image: curlimages/curl
    depends_on:
      kafka-connect:
        condition: service_healthy
      order_db:
        condition: service_healthy
    volumes:
      - ./debezium:/debezium
    entrypoint: [ "/bin/sh", "/debezium/register-connectors.sh" ]
    environment:
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

  auth_db:
    image: postgres:16
    container_name: auth_db
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB = ${POSTGRES_AUTH_DB}
    volumes:
      - auth_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  order_db:
    image: postgres:16
    container_name: order_db
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "max_wal_senders=4"
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB = ${POSTGRES_ORD_DB}
    volumes:
      - order_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory_db:
    image: postgres:16
    container_name: inventory_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB = ${POSTGRES_INV_DB}
    volumes:
      - inventory_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  notification_db:
    image: postgres:16
    container_name: notification_db
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB = ${POSTGRES_NOT_DB}
    volumes:
      - notification_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      - kafka

volumes:
  order_db:
  inventory_db:
  notification_db:
  auth_db:
  kafka_data:

