<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ks</groupId>
    <artifactId>web-shop</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.1</version>
    </parent>

    <modules>
        <module>gateway-service</module>
        <module>auth-service</module>
        <module>inventory-service</module>
        <module>notification-service</module>
        <module>order-service</module>
        <module>common.proto</module>
        <module>avro.order</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.3.1</spring.boot.version>
        <grpc.bom>1.78.0</grpc.bom>
        <protobuf.bom>3.25.1</protobuf.bom>
        <grpc.server.client.spring.boot.starter>3.1.0.RELEASE</grpc.server.client.spring.boot.starter>
        <common.proto>1.0.0</common.proto>
        <mapstruct>1.5.5.Final</mapstruct>
        <lombok>1.18.38</lombok>
        <maven.compiler.plugin>3.10.0</maven.compiler.plugin>
        <lombok.mapstruct.binding>0.2.0</lombok.mapstruct.binding>
        <avro>1.12.1</avro>
        <avro.order>1.0.0</avro.order>
        <kafka.avro.serializer>7.6.0</kafka.avro.serializer>
        <org.jetbrains.annotations>17.0.0</org.jetbrains.annotations>
        <commons.codec>1.18.0</commons.codec>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <io.jsonwebtoken>0.13.0</io.jsonwebtoken>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- gRPC BOM -->
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-bom</artifactId>
                <version>${grpc.bom}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Protobuf -->
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-bom</artifactId>
                <version>${protobuf.bom}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.ks</groupId>
                <artifactId>common-proto</artifactId>
                <version>${common.proto}</version>
            </dependency>

            <dependency>
                <groupId>net.devh</groupId>
                <artifactId>grpc-server-spring-boot-starter</artifactId>
                <version>${grpc.server.client.spring.boot.starter}</version>
            </dependency>

            <dependency>
                <groupId>net.devh</groupId>
                <artifactId>grpc-client-spring-boot-starter</artifactId>
                <version>${grpc.server.client.spring.boot.starter}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>${avro}</version>
            </dependency>

            <dependency>
                <groupId>io.confluent</groupId>
                <artifactId>kafka-avro-serializer</artifactId>
                <version>${kafka.avro.serializer}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>com.ks</groupId>
                <artifactId>avro-order</artifactId>
                <version>${avro.order}</version>
            </dependency>

            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>${org.jetbrains.annotations}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${commons.codec}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>


        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>

                <!-- Spring Boot -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>${lombok.mapstruct.binding}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>

        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/
            </url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
