--liquibase formatted sql

--changeset ks:000-create-outbox-order-table
--preconditions onFail:MARK_RAN
--precondition-not-table-exists tableName:outbox_event

CREATE TABLE outbox_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       UUID  NOT NULL UNIQUE,
    aggregate_type TEXT  NOT NULL,
    aggregate_id   UUID  NOT NULL,
    event_type     TEXT  NOT NULL,
    payload        BYTEA NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    schema_version INTEGER NOT NULL
);

CREATE INDEX idx_outbox_order_aggregate_id
    ON outbox_order (aggregate_id);

CREATE INDEX idx_outbox_order_created_at
    ON outbox_order (created_at);