--liquibase formatted sql

--changeset ks:000-create-orders-table
--preconditions onFail:MARK_RAN
--precondition-not-table-exists tableName:orders

CREATE TABLE orders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_uuid    UUID           NOT NULL UNIQUE,
    customer_uuid UUID           NOT NULL,
    status        TEXT           NOT NULL,
    total_price   NUMERIC(10, 2) NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--changeset ks:add-orders-status-check
ALTER TABLE orders
    ADD CONSTRAINT ck_orders_status
        CHECK (status IN ('NEW',
                          'UNPAID',
                          'PAID',
                          'CANCELED'));

--changeset ks:add-orders-updated-at-trigger

CREATE OR REPLACE FUNCTION set_orders_updated_at()
    RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_set_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
EXECUTE FUNCTION set_orders_updated_at();