--liquibase formatted sql

--changeset ks:000-create-items-table
--preconditions onFail:MARK_RAN
--precondition-not-table-exists tableName:items

CREATE TABLE items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     TEXT           NOT NULL,
    price    NUMERIC(10, 2) NOT NULL,
    quantity INTEGER        NOT NULL,
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    amount   NUMERIC(10, 2) NOT NULL,

    order_id BIGINT NOT NULL,

    CONSTRAINT fk_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders(id)
);

--changeset ks:add-items-order-index
CREATE INDEX idx_items_order_id
    ON items(order_id);