syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.ks.common.proto";
option java_outer_classname = "ProductProto";

service ProductService {
  rpc checkAvailability (ProductRequest) returns (ProductResponse);
}

message ProductRequest {
  int64 productId = 1;
}

message ProductResponse {
  int64 productId = 1;
  string productName = 2;
  int32 quantity = 3;
  Money price = 4;
  int32 sale = 5;
  Money totalPrice = 6;

  Availability availability = 7;
  bool degraded = 8;
}

message Money {
  int64 amount = 1; // сумма в минимальных единицах
  int32 scale = 2;  // количество знаков после запятой
}

enum Availability {
  AVAILABLE = 0;
  UNAVAILABLE = 1;
  UNKNOWN = 2;
}